language: objective-c
osx_image: xcode9
script:
    - xcodebuild clean build -sdk iphonesimulator -project ./SpriteAnimationDemo/SpriteAnimationDemo.xcodeproj -scheme SpriteAnimationDemo CODE_SIGNING_REQUIRED=NO